### ISSUE TITLE
[Question] Why unsigned long argument may be an obstacle to the control-flow integrity?

### ISSUE THREAD

**Issue by QiuhaoLi** [sysprog21/lkmpg#151]
In [13.2 Flashing keyboard LEDs](https://sysprog21.github.io/lkmpg/#flashing-keyboard-leds), it mentioned "Furthermore, the function prototype with unsigned long argument may be an obstacle to the control-flow integrity."

```c
struct timer_list { 
    unsigned long expires; 
    void (*function)(unsigned long);  // <---
    unsigned long data; 
    u32 flags; 
    /* ... */ 
}; 
```

**Could you make it clear why this argument prevents the control-flow integrity check?** As far as I know, hardware-assisted CFI like intel's [CET](https://www.intel.com/content/www/us/en/developer/articles/technical/technical-look-control-flow-enforcement-technology.html) uses shadow stack for ROP and IBT for JOP/COP, and there is nothing about parameters.

**Comment by linD026** [comment]
Hi @QiuhaoLi ,
The CFI, like the Clang option [here](https://clang.llvm.org/docs/ControlFlowIntegrity.html#indirect-function-call-checking), will check the dynamic type of indirect function call to match the static type correctly. 
This kind of function prototype changes with CFI is for **forward-edge protection**.
The shadow stack that you mentioned is for **backward-edge protection**.

For more information about timer API changes, you can see [this](https://lwn.net/Articles/735887/).
Also, here is the [commit](https://github.com/torvalds/linux/commit/686fef928bba6be13cabe639f154af7d72b63120) which changes the API.

---
We didn't mention it because it might be too deep for the beginner.
We will consider again if this kind of description is compatible.
But still, thank you for the feedback!

**Comment by QiuhaoLi** [comment]
Got it. Thanks for these helpful links! I think you can remove the paragraph about the API changes or give these links you mentioned (or maybe also [this one](https://nebelwelt.net/blog/20160913-ControlFlowIntegrity.html)) as additional read materials; otherwise, it's a little confusing for readers :)
